#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-rb-inotify
Version  : 0.9.5
Release  : 5
URL      : https://rubygems.org/downloads/rb-inotify-0.9.5.gem
Source0  : https://rubygems.org/downloads/rb-inotify-0.9.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-ffi
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-yard

%description
# rb-inotify
This is a simple wrapper over the [inotify](http://en.wikipedia.org/wiki/Inotify) Linux kernel subsystem
for monitoring changes to files and directories.
It uses the [FFI](http://wiki.github.com/ffi/ffi) gem to avoid having to compile a C extension.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n rb-inotify-0.9.5
gem spec %{SOURCE0} -l --ruby > rubygem-rb-inotify.gemspec

%build
gem build rubygem-rb-inotify.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
rb-inotify-0.9.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/rb-inotify-0.9.5.gem
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/.yardopts
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/README.md
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/lib/rb-inotify.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/lib/rb-inotify/event.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/lib/rb-inotify/native.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/lib/rb-inotify/native/flags.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/lib/rb-inotify/notifier.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/lib/rb-inotify/watcher.rb
/usr/lib64/ruby/gems/2.3.0/gems/rb-inotify-0.9.5/rb-inotify.gemspec
/usr/lib64/ruby/gems/2.3.0/specifications/rb-inotify-0.9.5.gemspec
